language: perl
sudo: false
perl:
  - "5.26"
install:
  - cpanm --notest Dancer2
#  - cpanm --notest Devel::Cover::Report::Coveralls
#  - cpanm --notest Test::Code::TidyAll 
#  - cpanm --notest Test::Perl::Critic
#  - cpanm --notest Test::Version
script:
  - prove -r
